### ISSUE TITLE
If the root is the source dir (-i.) then it reports Setup.hs and others as conflicting "Main"s

### ISSUE THREAD

**Issue by Peaker** [soenkehahn/dead-code-detection#11]

**Comment by Peaker** [comment]
```
Some of the input files produce compile errors.
ghc says:
   module ‘Main’ is defined in multiple files: ./Lamdu/Main.hs
                                               ./Setup.hs 
                                               ...
```

**Comment by soenkehahn** [comment]
Thanks for the report!

You can pass `--ignore Setup.hs` to work around this.

(Ignoring files was very unreliable, I've just released version `0.8` to hackage which fixes that.)

Would you consider this issue fixed through `--ignore` then? There's other options what `dead-code-detection` could do:
- In case of multiple `Main` modules mention that `--ignore` exists.
- Ignore `./Setup.hs` always.
- Ignore `./Setup.hs` by default, allow to override with `--ignore something`.

Any opinions? Any urge to write PRs for any of this? ;)

**Comment by Peaker** [comment]
Thanks for the reply.
Ignore would be helpful :)

I actually have about 6 more tool mains but I'll ignore em all.

**Comment by soenkehahn** [comment]
> Ignore would be helpful :)

`--ignore` already exists.

Not sure, but does this solve your issue? Can this be closed then?

**Comment by Peaker** [comment]
Yes, `--ignore` is fine.
