### ISSUE TITLE
Version on stackage does not build with GHC 8

### ISSUE THREAD

**Issue by metaleap** [soenkehahn/dead-code-detection#14]
Error details upon `stack install dead-code-detection`:

    C:\Users\roxor\AppData\Local\Temp\stack5720\dead-code-detection-0.8.1\src\Ast\UsedNames.hs:28:5: error:
        * The constructor `FunBind' should have 5 arguments, but has been given 6
        * In the pattern: FunBind _ _ matches _ _ _
          In a case alternative:
              FunBind _ _ matches _ _ _ -> usedNames matches
          In the expression:
            \case {
              FunBind _ _ matches _ _ _ -> usedNames matches
              PatBind lhs rhs _ _ _ -> usedNames lhs ++ usedNames rhs
              x -> errorNyiOutputable x }

    C:\Users\roxor\AppData\Local\Temp\stack5720\dead-code-detection-0.8.1\src\Ast\UsedNames.hs:76:5: error:
        * The constructor `BindStmt' should have 5 arguments, but has been given 4
        * In the pattern: BindStmt pat expr _ _
          In a case alternative:
              BindStmt pat expr _ _ -> usedNames pat ++ usedNames expr
          In the expression:
            \case {
              BindStmt pat expr _ _ -> usedNames pat ++ usedNames expr
              LastStmt expr _ -> usedNames expr
              BodyStmt expr _ _ _ -> usedNames expr
              LetStmt x -> usedNames x
              x -> errorNyiOutputable x }

    C:\Users\roxor\AppData\Local\Temp\stack5720\dead-code-detection-0.8.1\src\Ast\UsedNames.hs:105:5: error:
        * The constructor `RecordUpd' should have 6 arguments, but has been given 5
        * In the pattern: RecordUpd expr recordBinds [] _ _
          In a case alternative:
              RecordUpd expr recordBinds [] _ _
                -> usedNames expr ++ usedNames recordBinds
          In the expression:
            \case {
              HsVar n -> [n]
              HsLet binds expr -> usedNames binds ++ usedNames expr
              HsLit _ -> []
              HsApp f x -> usedNames f ++ usedNames x
              OpApp a op _ b -> usedNames a ++ usedNames op ++ usedNames b
              HsPar x -> usedNames x
              ExplicitList _ Nothing list -> usedNames list
              ExplicitTuple exprs _ -> usedNames exprs
              HsOverLit {} -> []
              HsLam x -> usedNames x
              HsDo context stmts _ -> usedNames context ++ usedNames stmts
              SectionL a b -> usedNames a ++ usedNames b
              SectionR a b -> usedNames a ++ usedNames b
              HsCase on matchGroup -> usedNames on ++ usedNames matchGroup
              RecordUpd expr recordBinds [] _ _
                -> usedNames expr ++ usedNames recordBinds
              HsLamCase _ matchGroup -> usedNames matchGroup
              HsIf _ c t e -> usedNames c ++ usedNames t ++ usedNames e
              ExprWithTySig expr _ _ -> usedNames expr
              NegApp expr _ -> usedNames expr
              ArithSeq _ _ info -> usedNames info
              RecordCon constructor _ binds
                -> unLoc constructor : usedNames binds
              x -> errorNyiOutputable x }

    C:\Users\roxor\AppData\Local\Temp\stack5720\dead-code-detection-0.8.1\src\Ast\UsedNames.hs:159:5: error:
        * Couldn't match type `FieldOcc Name' with `Name'
          Expected type: [Name]
            Actual type: [FieldOcc Name]
        * In the expression: unLoc assigned : usedNames expr
          In an equation for `usedNames':
              usedNames (HsRecField assigned expr _)
                = unLoc assigned : usedNames expr
          In the instance declaration for `UsedNames (HsRecField Name arg)'

    C:\Users\roxor\AppData\Local\Temp\stack5720\dead-code-detection-0.8.1\src\Ast\UsedNames.hs:159:22: error:
        * Couldn't match type `Name' with `FieldOcc Name'
          Expected type: [FieldOcc Name]
            Actual type: [Name]
        * In the second argument of `(:)', namely `usedNames expr'
          In the expression: unLoc assigned : usedNames expr
          In an equation for `usedNames':
              usedNames (HsRecField assigned expr _)
                = unLoc assigned : usedNames expr

**Comment by metaleap** [comment]
OK that's only with GHC 8.0.2 (the current), with `stack install --install-ghc` it fetches GHC 7.10.3 and then builds `dead-code-detection` successfully.

Can close this --- unless you want to keep it in this *Open Issues* list for others to see easily or to later remember to bring the project up-to-speed with current-gen compiler versions  ;)

**Comment by soenkehahn** [comment]
`stack.yaml` states that this should be built with `lts-5.8` which implies `ghc-7.10.3`. I'm surpised `stack install dead-code-detection` attempts to build this with another compiler version. (cc: @borsboom @mgsloan, in case you're interested.)

Anyway, closing this in favor of #15, which will include updating to `ghc-8`.

**Comment by metaleap** [comment]
Yeah sorry my bad, I always try my own preferred (8.0.2 currently) resolver first to see if it builds with that, often avoiding lengthy downloads/installs that way. Was too hasty to post this.

**Comment by soenkehahn** [comment]
@metaleap: No problem. Just to clarify: Are you saying you deleted or modified the stack file to try to build with `8.0.2`?

**Comment by metaleap** [comment]
No I just tend to add `--resolver=ghc-8.0.2` at first when installing new packages whenever I remember to; such was the case here iirc
